-- MySQL Script generated by MySQL Workbench
-- Tue Sep  9 18:02:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alunos` (
  `id` INT NOT NULL,
  `nome_Aluno` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos` (
  `id` INT NULL,
  `nome_curso` VARCHAR(45) NOT NULL,
  `carga-horaria` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`matriculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`matriculas` (
  `id` INT NOT NULL,
  `cursos_id` INT NOT NULL,
  `data_matricula` DATE NULL,
  `alunos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_matriculas_cursos`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `mydb`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matriculas_alunos1`
    FOREIGN KEY (`alunos_id`)
    REFERENCES `mydb`.`alunos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alunos_has_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alunos_has_cursos` (
  `alunos_id` INT NOT NULL,
  `cursos_id` INT NOT NULL,
  PRIMARY KEY (`alunos_id`, `cursos_id`),
  INDEX `fk_alunos_has_cursos_cursos1_idx` (`cursos_id` ASC) VISIBLE,
  INDEX `fk_alunos_has_cursos_alunos1_idx` (`alunos_id` ASC) VISIBLE,
  CONSTRAINT `fk_alunos_has_cursos_alunos1`
    FOREIGN KEY (`alunos_id`)
    REFERENCES `mydb`.`alunos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alunos_has_cursos_cursos1`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `mydb`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO alunos(nome_Aluno,email,data_Nascimento) VALUES
('Daniel Melo', 'daniel@gmail.com', '2006-09-12'),
('Nethanyas Domigos', 'nethanuas@gmail.com', '2010-08-06'),
('Dinea Gisele Kostetzer Bruch', 'dineagisele@gmail.com', '1979-01-09'),
('Suelen Tais Kostetzer', 'suelen@gmail.com', '1982-23-05'),
('Geisa Cristina Kostetzer', 'geisa@gmail.com', '1980-01-09'),
('Samuel Richard Bruch', 'samuel@gmail.com', '2006-06-06');

INSERT INTO matriculas(data_matricula) VALUES
('2025-02-03'),
('2025-03-04'),
('2025-04-06'),
('2025-02-06'),
('2025-01-06'),
('2025-03-06'),
('2025-05-06'),
('2025-07-06'),
('2025-08-06'),
('2025-10-06');

INSERT INTO cursos (nome,carga_horaria) VALUES
('Programacao', '200'),
('Meio-Ambiente', '20'),
('Informatica Basica', '30');